# syntax=docker/compose:1.29.0
# Production override - use with: docker compose -f compose.yaml -f compose.prod.yaml up
version: '3.9'

services:
  backend:
    restart: always
    environment:
      - WORKERS=2
    volumes: []
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M

  frontend:
    restart: always
    volumes: []
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  db:
    restart: always
    ports: []
    environment:
      - POSTGRES_INITDB_ARGS=-c max_connections=100
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
